$(document).ready(function(){
  $('.parallax').parallax();
});
$(document).ready(function(){
  $('.materialboxed').materialbox();
});
$(document).ready(function(){
  $('.materialboxed').materialbox();
});
